<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="OpenTK.Mathematics" Version="4.9.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsynCUDA13.Shared\AsynCUDA13.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Kernels\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
