<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ViewModels\FractalsViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="ViewModels\FractalsViewModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Radzen.Blazor" Version="11.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsynCUDA13.Client\AsynCUDA13.Client.csproj" />
    <ProjectReference Include="..\AsynCUDA13.Shared\AsynCUDA13.Shared.csproj" />
  </ItemGroup>

</Project>
